DELETE http://localhost:8080/delete/diary?date=2022-05-05
Accept: application/json

###
PUT http://localhost:8080/update/diary?date=2022-05-20
Accept: text/html

this is new idary text

###
GET http://localhost:8080/read/diaries?startDate=2022-05-05&endDate=2022-05-20
Accept: application/json

###
### readDiary
GET http://localhost:8080/read/diary?date=2022-05-20
Accept: application/json

### getWeather
POST http://localhost:8080/create/diary?date=2022-05-01
Content-Type: text/html

i want to learn spring boot
###

